//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientePersonas.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntRespuesta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EntRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientePersonas.ServiceReference1.ArrayOfPersona ListaPersonasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientePersonas.ServiceReference1.persona PersonasField;
        
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebClientePersonas.ServiceReference1.ArrayOfPersona ListaPersonas {
            get {
                return this.ListaPersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPersonasField, value) != true)) {
                    this.ListaPersonasField = value;
                    this.RaisePropertyChanged("ListaPersonas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebClientePersonas.ServiceReference1.persona Personas {
            get {
                return this.PersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasField, value) != true)) {
                    this.PersonasField = value;
                    this.RaisePropertyChanged("Personas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternoField;
        
        private System.DateTime FechaAltaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Paterno {
            get {
                return this.PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternoField, value) != true)) {
                    this.PaternoField = value;
                    this.RaisePropertyChanged("Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Materno {
            get {
                return this.MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternoField, value) != true)) {
                    this.MaternoField = value;
                    this.RaisePropertyChanged("Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaAlta {
            get {
                return this.FechaAltaField;
            }
            set {
                if ((this.FechaAltaField.Equals(value) != true)) {
                    this.FechaAltaField = value;
                    this.RaisePropertyChanged("FechaAlta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPersona", Namespace="http://tempuri.org/", ItemName="persona")]
    [System.SerializableAttribute()]
    public class ArrayOfPersona : System.Collections.Generic.List<WebClientePersonas.ServiceReference1.persona> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServicePersonasSoap")]
    public interface WebServicePersonasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener", ReplyAction="*")]
        WebClientePersonas.ServiceReference1.ObtenerResponse Obtener(WebClientePersonas.ServiceReference1.ObtenerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.ObtenerResponse> ObtenerAsync(WebClientePersonas.ServiceReference1.ObtenerRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerPorIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPorId", ReplyAction="*")]
        WebClientePersonas.ServiceReference1.ObtenerPorIdResponse ObtenerPorId(WebClientePersonas.ServiceReference1.ObtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.ObtenerPorIdResponse> ObtenerPorIdAsync(WebClientePersonas.ServiceReference1.ObtenerPorIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento p del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        WebClientePersonas.ServiceReference1.AgregarResponse Agregar(WebClientePersonas.ServiceReference1.AgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.AgregarResponse> AgregarAsync(WebClientePersonas.ServiceReference1.AgregarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento p del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Editar", ReplyAction="*")]
        WebClientePersonas.ServiceReference1.EditarResponse Editar(WebClientePersonas.ServiceReference1.EditarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Editar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.EditarResponse> EditarAsync(WebClientePersonas.ServiceReference1.EditarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento p del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Borrar", ReplyAction="*")]
        WebClientePersonas.ServiceReference1.BorrarResponse Borrar(WebClientePersonas.ServiceReference1.BorrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Borrar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.BorrarResponse> BorrarAsync(WebClientePersonas.ServiceReference1.BorrarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento p del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarNombreRepetido", ReplyAction="*")]
        WebClientePersonas.ServiceReference1.ValidarNombreRepetidoResponse ValidarNombreRepetido(WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarNombreRepetido", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.ValidarNombreRepetidoResponse> ValidarNombreRepetidoAsync(WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obtener", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.ObtenerRequestBody Body;
        
        public ObtenerRequest() {
        }
        
        public ObtenerRequest(WebClientePersonas.ServiceReference1.ObtenerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerRequestBody {
        
        public ObtenerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.ObtenerResponseBody Body;
        
        public ObtenerResponse() {
        }
        
        public ObtenerResponse(WebClientePersonas.ServiceReference1.ObtenerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClientePersonas.ServiceReference1.EntRespuesta ObtenerResult;
        
        public ObtenerResponseBody() {
        }
        
        public ObtenerResponseBody(WebClientePersonas.ServiceReference1.EntRespuesta ObtenerResult) {
            this.ObtenerResult = ObtenerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPorId", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.ObtenerPorIdRequestBody Body;
        
        public ObtenerPorIdRequest() {
        }
        
        public ObtenerPorIdRequest(WebClientePersonas.ServiceReference1.ObtenerPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerPorIdRequestBody() {
        }
        
        public ObtenerPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.ObtenerPorIdResponseBody Body;
        
        public ObtenerPorIdResponse() {
        }
        
        public ObtenerPorIdResponse(WebClientePersonas.ServiceReference1.ObtenerPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClientePersonas.ServiceReference1.persona ObtenerPorIdResult;
        
        public ObtenerPorIdResponseBody() {
        }
        
        public ObtenerPorIdResponseBody(WebClientePersonas.ServiceReference1.persona ObtenerPorIdResult) {
            this.ObtenerPorIdResult = ObtenerPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Agregar", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.AgregarRequestBody Body;
        
        public AgregarRequest() {
        }
        
        public AgregarRequest(WebClientePersonas.ServiceReference1.AgregarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClientePersonas.ServiceReference1.persona p;
        
        public AgregarRequestBody() {
        }
        
        public AgregarRequestBody(WebClientePersonas.ServiceReference1.persona p) {
            this.p = p;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.AgregarResponseBody Body;
        
        public AgregarResponse() {
        }
        
        public AgregarResponse(WebClientePersonas.ServiceReference1.AgregarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClientePersonas.ServiceReference1.EntRespuesta AgregarResult;
        
        public AgregarResponseBody() {
        }
        
        public AgregarResponseBody(WebClientePersonas.ServiceReference1.EntRespuesta AgregarResult) {
            this.AgregarResult = AgregarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Editar", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.EditarRequestBody Body;
        
        public EditarRequest() {
        }
        
        public EditarRequest(WebClientePersonas.ServiceReference1.EditarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClientePersonas.ServiceReference1.persona p;
        
        public EditarRequestBody() {
        }
        
        public EditarRequestBody(WebClientePersonas.ServiceReference1.persona p) {
            this.p = p;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.EditarResponseBody Body;
        
        public EditarResponse() {
        }
        
        public EditarResponse(WebClientePersonas.ServiceReference1.EditarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditarResponseBody {
        
        public EditarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Borrar", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.BorrarRequestBody Body;
        
        public BorrarRequest() {
        }
        
        public BorrarRequest(WebClientePersonas.ServiceReference1.BorrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BorrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClientePersonas.ServiceReference1.persona p;
        
        public BorrarRequestBody() {
        }
        
        public BorrarRequestBody(WebClientePersonas.ServiceReference1.persona p) {
            this.p = p;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.BorrarResponseBody Body;
        
        public BorrarResponse() {
        }
        
        public BorrarResponse(WebClientePersonas.ServiceReference1.BorrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BorrarResponseBody {
        
        public BorrarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarNombreRepetidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarNombreRepetido", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequestBody Body;
        
        public ValidarNombreRepetidoRequest() {
        }
        
        public ValidarNombreRepetidoRequest(WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarNombreRepetidoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClientePersonas.ServiceReference1.persona p;
        
        public ValidarNombreRepetidoRequestBody() {
        }
        
        public ValidarNombreRepetidoRequestBody(WebClientePersonas.ServiceReference1.persona p) {
            this.p = p;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarNombreRepetidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarNombreRepetidoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClientePersonas.ServiceReference1.ValidarNombreRepetidoResponseBody Body;
        
        public ValidarNombreRepetidoResponse() {
        }
        
        public ValidarNombreRepetidoResponse(WebClientePersonas.ServiceReference1.ValidarNombreRepetidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarNombreRepetidoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClientePersonas.ServiceReference1.EntRespuesta ValidarNombreRepetidoResult;
        
        public ValidarNombreRepetidoResponseBody() {
        }
        
        public ValidarNombreRepetidoResponseBody(WebClientePersonas.ServiceReference1.EntRespuesta ValidarNombreRepetidoResult) {
            this.ValidarNombreRepetidoResult = ValidarNombreRepetidoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePersonasSoapChannel : WebClientePersonas.ServiceReference1.WebServicePersonasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePersonasSoapClient : System.ServiceModel.ClientBase<WebClientePersonas.ServiceReference1.WebServicePersonasSoap>, WebClientePersonas.ServiceReference1.WebServicePersonasSoap {
        
        public WebServicePersonasSoapClient() {
        }
        
        public WebServicePersonasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePersonasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePersonasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePersonasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientePersonas.ServiceReference1.ObtenerResponse WebClientePersonas.ServiceReference1.WebServicePersonasSoap.Obtener(WebClientePersonas.ServiceReference1.ObtenerRequest request) {
            return base.Channel.Obtener(request);
        }
        
        public WebClientePersonas.ServiceReference1.EntRespuesta Obtener() {
            WebClientePersonas.ServiceReference1.ObtenerRequest inValue = new WebClientePersonas.ServiceReference1.ObtenerRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.ObtenerRequestBody();
            WebClientePersonas.ServiceReference1.ObtenerResponse retVal = ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).Obtener(inValue);
            return retVal.Body.ObtenerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.ObtenerResponse> WebClientePersonas.ServiceReference1.WebServicePersonasSoap.ObtenerAsync(WebClientePersonas.ServiceReference1.ObtenerRequest request) {
            return base.Channel.ObtenerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.ObtenerResponse> ObtenerAsync() {
            WebClientePersonas.ServiceReference1.ObtenerRequest inValue = new WebClientePersonas.ServiceReference1.ObtenerRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.ObtenerRequestBody();
            return ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).ObtenerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientePersonas.ServiceReference1.ObtenerPorIdResponse WebClientePersonas.ServiceReference1.WebServicePersonasSoap.ObtenerPorId(WebClientePersonas.ServiceReference1.ObtenerPorIdRequest request) {
            return base.Channel.ObtenerPorId(request);
        }
        
        public WebClientePersonas.ServiceReference1.persona ObtenerPorId(int id) {
            WebClientePersonas.ServiceReference1.ObtenerPorIdRequest inValue = new WebClientePersonas.ServiceReference1.ObtenerPorIdRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.ObtenerPorIdRequestBody();
            inValue.Body.id = id;
            WebClientePersonas.ServiceReference1.ObtenerPorIdResponse retVal = ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).ObtenerPorId(inValue);
            return retVal.Body.ObtenerPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.ObtenerPorIdResponse> WebClientePersonas.ServiceReference1.WebServicePersonasSoap.ObtenerPorIdAsync(WebClientePersonas.ServiceReference1.ObtenerPorIdRequest request) {
            return base.Channel.ObtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.ObtenerPorIdResponse> ObtenerPorIdAsync(int id) {
            WebClientePersonas.ServiceReference1.ObtenerPorIdRequest inValue = new WebClientePersonas.ServiceReference1.ObtenerPorIdRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.ObtenerPorIdRequestBody();
            inValue.Body.id = id;
            return ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).ObtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientePersonas.ServiceReference1.AgregarResponse WebClientePersonas.ServiceReference1.WebServicePersonasSoap.Agregar(WebClientePersonas.ServiceReference1.AgregarRequest request) {
            return base.Channel.Agregar(request);
        }
        
        public WebClientePersonas.ServiceReference1.EntRespuesta Agregar(WebClientePersonas.ServiceReference1.persona p) {
            WebClientePersonas.ServiceReference1.AgregarRequest inValue = new WebClientePersonas.ServiceReference1.AgregarRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.AgregarRequestBody();
            inValue.Body.p = p;
            WebClientePersonas.ServiceReference1.AgregarResponse retVal = ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).Agregar(inValue);
            return retVal.Body.AgregarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.AgregarResponse> WebClientePersonas.ServiceReference1.WebServicePersonasSoap.AgregarAsync(WebClientePersonas.ServiceReference1.AgregarRequest request) {
            return base.Channel.AgregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.AgregarResponse> AgregarAsync(WebClientePersonas.ServiceReference1.persona p) {
            WebClientePersonas.ServiceReference1.AgregarRequest inValue = new WebClientePersonas.ServiceReference1.AgregarRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.AgregarRequestBody();
            inValue.Body.p = p;
            return ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).AgregarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientePersonas.ServiceReference1.EditarResponse WebClientePersonas.ServiceReference1.WebServicePersonasSoap.Editar(WebClientePersonas.ServiceReference1.EditarRequest request) {
            return base.Channel.Editar(request);
        }
        
        public void Editar(WebClientePersonas.ServiceReference1.persona p) {
            WebClientePersonas.ServiceReference1.EditarRequest inValue = new WebClientePersonas.ServiceReference1.EditarRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.EditarRequestBody();
            inValue.Body.p = p;
            WebClientePersonas.ServiceReference1.EditarResponse retVal = ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).Editar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.EditarResponse> WebClientePersonas.ServiceReference1.WebServicePersonasSoap.EditarAsync(WebClientePersonas.ServiceReference1.EditarRequest request) {
            return base.Channel.EditarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.EditarResponse> EditarAsync(WebClientePersonas.ServiceReference1.persona p) {
            WebClientePersonas.ServiceReference1.EditarRequest inValue = new WebClientePersonas.ServiceReference1.EditarRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.EditarRequestBody();
            inValue.Body.p = p;
            return ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).EditarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientePersonas.ServiceReference1.BorrarResponse WebClientePersonas.ServiceReference1.WebServicePersonasSoap.Borrar(WebClientePersonas.ServiceReference1.BorrarRequest request) {
            return base.Channel.Borrar(request);
        }
        
        public void Borrar(WebClientePersonas.ServiceReference1.persona p) {
            WebClientePersonas.ServiceReference1.BorrarRequest inValue = new WebClientePersonas.ServiceReference1.BorrarRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.BorrarRequestBody();
            inValue.Body.p = p;
            WebClientePersonas.ServiceReference1.BorrarResponse retVal = ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).Borrar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.BorrarResponse> WebClientePersonas.ServiceReference1.WebServicePersonasSoap.BorrarAsync(WebClientePersonas.ServiceReference1.BorrarRequest request) {
            return base.Channel.BorrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.BorrarResponse> BorrarAsync(WebClientePersonas.ServiceReference1.persona p) {
            WebClientePersonas.ServiceReference1.BorrarRequest inValue = new WebClientePersonas.ServiceReference1.BorrarRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.BorrarRequestBody();
            inValue.Body.p = p;
            return ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).BorrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientePersonas.ServiceReference1.ValidarNombreRepetidoResponse WebClientePersonas.ServiceReference1.WebServicePersonasSoap.ValidarNombreRepetido(WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequest request) {
            return base.Channel.ValidarNombreRepetido(request);
        }
        
        public WebClientePersonas.ServiceReference1.EntRespuesta ValidarNombreRepetido(WebClientePersonas.ServiceReference1.persona p) {
            WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequest inValue = new WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequestBody();
            inValue.Body.p = p;
            WebClientePersonas.ServiceReference1.ValidarNombreRepetidoResponse retVal = ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).ValidarNombreRepetido(inValue);
            return retVal.Body.ValidarNombreRepetidoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.ValidarNombreRepetidoResponse> WebClientePersonas.ServiceReference1.WebServicePersonasSoap.ValidarNombreRepetidoAsync(WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequest request) {
            return base.Channel.ValidarNombreRepetidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClientePersonas.ServiceReference1.ValidarNombreRepetidoResponse> ValidarNombreRepetidoAsync(WebClientePersonas.ServiceReference1.persona p) {
            WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequest inValue = new WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequest();
            inValue.Body = new WebClientePersonas.ServiceReference1.ValidarNombreRepetidoRequestBody();
            inValue.Body.p = p;
            return ((WebClientePersonas.ServiceReference1.WebServicePersonasSoap)(this)).ValidarNombreRepetidoAsync(inValue);
        }
    }
}
